name: Build and Publish Docker Image to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
    branches:
      - main  # Trigger on pushes to the `main` branch
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # This permission is essential for publishing to ghcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        if: runner.arch != 'ARM64' # Only needed for cross-compilation
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Packages Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set image tags
        id: set_tags
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/devcontainer"
          TAGS="${IMAGE_NAME}:${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            TAGS="${IMAGE_NAME}:latest"
          fi
          echo "IMAGE_TAGS=$TAGS" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Path to the Dockerfile
          push: true  # Push the image to the registry
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/amd64,linux/arm64  # Multi-architecture platforms
          provenance: false
          sbom: false